services:
  # ------------ Postgres (B-Tree) ------------
  postgres:
    image: postgres:16
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bench
    ports:
      - "5432:5432"
    mem_limit: 1024m
    memswap_limit: 1024m
    volumes:
      # host-path : container-path
      - ./data/pg_data:/var/lib/postgresql/data

  # ------------ Kvrocks (Redis protocol, RocksDB) ------------
  kvrocks:
    image: apache/kvrocks:latest
    container_name: kvrocks
    restart: unless-stopped
    command: >
      --bind 0.0.0.0
      --max-background-jobs 4
      --write-buffer-size    128m
      --disable_wal          1
    ports:
      - "6666:6666"
    mem_limit: 1024m
    memswap_limit: 1024m
    volumes:
      - ./data/kv_data:/var/lib/kvrocks/db         # mount host folder at default dir