services:
  cass1:
    image: cassandra:4.1
    container_name: cass1
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: cass1,cass2,cass3
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    networks: [cass-net]
    ports: ["9042:9042"]

  cass2:
    image: cassandra:4.1
    container_name: cass2
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: cass1,cass2,cass3
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    networks: [cass-net]
    ports: ["9043:9042"]
    depends_on: [cass1]

  cass3:
    image: cassandra:4.1
    container_name: cass3
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: cass1,cass2,cass3
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    networks: [cass-net]
    ports: ["9044:9042"]
    depends_on: [cass1]

networks:
  cass-net:
